### ISSUE TITLE
Unable to get GPU to handle conversion

### ISSUE THREAD

**Issue by acrane1** [zocker-160/handbrake-nvenc-docker#10]
I am trying to setup Handbrake to work with my NVIDIA GeForce GTX 1660 SUPER. But No matter what I choose it always runs on my CPU, and nothing shows up on nvtop. The GPU works with other containers like Compressarr, and Emby.

docker run -d --name='HandBrake' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'AUTOMATED_CONVERSION_PRESET'='Hardware/H.265 NVENC 1080p' -e 'AUTOMATED_CONVERSION_FORMAT'='mkv' -e 'AUTOMATED_CONVERSION_KEEP_SOURCE'='1' -e 'AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION'='ignore' -e 'AUTOMATED_CONVERSION_OUTPUT_DIR'='/output' -e 'AUTOMATED_CONVERSION_OUTPUT_SUBDIR'='' -e 'NVIDIA_DRIVER_CAPABILITIES'='all' -e 'NVIDIA_VISIBLE_DEVICES'='GPU-d85ebfd2-6e96-4b1c-8f3e-4e85487c4e92' -e 'USER_ID'='99' -e 'GROUP_ID'='100' -e 'UMASK'='000' -e 'APP_NICENESS'='' -e 'DISPLAY_WIDTH'='1280' -e 'DISPLAY_HEIGHT'='768' -e 'SECURE_CONNECTION'='0' -e 'X11VNC_EXTRA_OPTS'='' -e 'AUTOMATED_CONVERSION_VIDEO_FILE_EXTENSIONS'='' -e 'AUTOMATED_CONVERSION_NON_VIDEO_FILE_EXTENSIONS'='jpg jpeg bmp png gif txt nfo' -e 'AUTOMATED_CONVERSION_OVERWRITE_OUTPUT'='0' -e 'AUTOMATED_CONVERSION_SOURCE_STABLE_TIME'='5' -e 'AUTOMATED_CONVERSION_SOURCE_MIN_DURATION'='10' -e 'AUTOMATED_CONVERSION_CHECK_INTERVAL'='5' -e 'AUTOMATED_CONVERSION_MAX_WATCH_FOLDERS'='5' -e 'AUTOMATED_CONVERSION_NO_GUI_PROGRESS'='0' -e 'AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS'='' -e 'AUTOMATED_CONVERSION_INSTALL_PKGS'='' -p '7803:5800/tcp' -p '7903:5900/tcp' -v '/mnt/user/Media/':'/storage':'ro' -v '/mnt/user/Media/Watch/':'/watch':'rw' -v '/mnt/user/Media/Compressarr/':'/output':'rw' -v '/mnt/user/appdata/HandBrake':'/config':'rw' --runtime=nvidia --gpus all 'zocker/handbrake'

OS: Unraid 6.8.2
Handbrake Versions: 1.4.2

I have tried with NVIDIA_VISIBLE_DEVICES set to all, I have also tried with and without environment flags --runtime=nvidia --gpus all
I 've ensured it's using the Hardware/H.265 NVENC 1080p profile

**Comment by acrane1** [comment]
Please close. I realized I was not using the NVENC image.

**Comment by zocker-160** [comment]
for future reference:
your command above does look alright except for the image name part since `'zocker/handbrake'` does not exist. As long as you use `zocker160/handbrake-nvenc` with the tags specified in the readme, you should be good.

I will close this then.
