### ISSUE TITLE
handbrake - nvenc 265 10 bit

### ISSUE THREAD

**Issue by repomanz** [zocker-160/handbrake-nvenc-docker#12]
Hi Dev - 

Do you have any plans on updating this container to support nvenc 265 10 bit encoding?  Doing some reading, looks like handbrake is capable of this in their main fork or nightly snapshots.

**Comment by zocker-160** [comment]
Hi,

I am following the stable releases of the Handbrake project and the latest version as of today is 1.5.1 which this container is currently using.

I see that 1.6.0 has been tagged 3 hours ago, so the moment it is available [here](https://github.com/HandBrake/HandBrake/releases) I will update as well.

**Comment by repomanz** [comment]
Thanks!

**Comment by zocker-160** [comment]
Update to 1.6.0 is pushed, it should be available on docker hub in ~30 minutes.
