### ISSUE TITLE
Add Handbrake nightly support for newest features

### ISSUE THREAD

**Issue by ApfelBirneKreis** [zocker-160/handbrake-nvenc-docker#16]
Pls add Handbrake nightly Support

**Comment by zocker-160** [comment]
While generally this is possible to do with a nightly workflow, I won't be able to check constantly if the build is actually working or not.

**Comment by zocker-160** [comment]
> Also would it be possible to import the intel wave container toolkit?

Can you elaborate a bit, I hear about this for the first time.
