### ISSUE TITLE
Encoding with non-NVENC h265 too slow

### ISSUE THREAD

**Issue by conkydong** [zocker-160/handbrake-nvenc-docker#2]
Encoding with non-NVENC h265 too slow.
Do I have to configure something for it to work as expected?

**Comment by zocker-160** [comment]
can you provide some more information? 
How do you know that it is too slow, compared to what?
are all CPU cores loaded?
how fast is it with which settings?

non NVENC obviously uses only CPU which is way slower compared to NVENC

**Comment by conkydong** [comment]
Sorry, never mind. I completely ignored the fact, that the CPU cores of my NAS, on which I tried to encode just have a maximum of 2,5 GHZ and my PCs CPU cores about 4 GHZ.
