### ISSUE TITLE
Has anyone got 18x  with NVENC working in Ubuntu 24.04?

### ISSUE THREAD

**Issue by smurfanders** [zocker-160/handbrake-nvenc-docker#20]
Hi,

I just updated my Ubuntu installation from 22.04 to 24.04 and now Handbrake refuses to encode NVENC. In the activity log inside the Handbrake GUI i get "Cannot load libnvidia-encode.so.1". On the host machine I can see the Nvidia card in nvidia-smi but in the Handbrake GUI I can't choose NVENC anymore.

Hope anyone has some advise, if you need logs or something please explain how to find the correct ones.

With regards -=/Anders

**Comment by zocker-160** [comment]
Are you sure your Nvidia driver is correctly installed? 
I myself am on a Ubuntu 24.04 installation upgraded from 22.04 just a few days ago and I can use the GPU as expected.

**Comment by smurfanders** [comment]
I have uninstalled and reinstalled the driver (v 550.90.07) but something is wrong, just can't figure out what.

**Comment by zocker-160** [comment]
Check if you have the library installed on the system using 
```
find /usr/lib -type f -name libnvidia-encode.so*
```
it should return something like this
```
/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.550.107.02
/usr/lib/i386-linux-gnu/libnvidia-encode.so.550.107.02
```

**Comment by smurfanders** [comment]
I get this: 
/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.550.90.07

**Comment by smurfanders** [comment]
Got it working, finally. Reinstalled all the drivers and all utils, encoders and so on manually. Also had to enable the full gpu under nvidia runtime in the docker compose yaml.
