### ISSUE TITLE
Error when starting container: "docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]."

### ISSUE THREAD

**Issue by matze0301** [zocker-160/handbrake-nvenc-docker#22]
When starting, i get the following error (removed the volumes lines for privacy reason):

```
docker run -d -t \
    --name=handbrake \
    -p 5800:5800 \
    --gpus all \
    zocker160/handbrake-nvenc:latest
d279c149e996195a523b63f7ec4ed27ac23e51a0051b1de2d00994f51544ced5
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

Docker container is in status "Created" and not "Up"

Can someone suggest a solution?
Do i need to provide additional infos?

**Comment by matze0301** [comment]
After installing nvidia-container-toolkit and nvidia-container-toolkit the container starts and i can select NVEnc Encoders.
Now i will check if it works.

**Comment by zocker-160** [comment]
In case you are running on Debian headless, please make sure you install the official nvidia driver, the one from the Debian repository could cause issues with NVenc.

**Comment by matze0301** [comment]
Thank you very much for your support :-)
I installed official nvidia drivers from nvdia repo (i'm on Ubuntu 24.04 LTS)

Is there a website where i can place a question i still have, but it's probably not an issue with this repo.
(When encoding with NVEnc, destination files are about the same size as source, tested with H.264 NVEnc, H.265 NVEnc and H.265 10-bit NVEnc. With H.264 (x264)  and all other settings the same, destination size is about 1/3 of source)

**Comment by zocker-160** [comment]
Glad to hear that you got it working.

Regarding your other question, to me this sounds pretty normal, NVEnc simply does not compress as well as when using x264 CPU encoding especially if you want high quality. 
Depending on your quality settings and the bitrate, it can in fact even be worse than a very high quality x264 preset.

Furthermore it also depends on your hardware, for example a GTX 1080ti produces way worse quality for the same bitrate than a 4090.

**Comment by matze0301** [comment]
` and all other settings the same`
I was wrong here.
I played with CQ, which initially was at 15. With CQ 23 i have indeed reduced filesizes and it's about 10x faster with NVEnc than without (RTX 3070 ti)

Thank you again for your support and this repo :-)

**Comment by zocker-160** [comment]
ah alright, although with CQ23 you are losing quite a bit of quality though?

**Comment by matze0301** [comment]
Not noticeable, so i'll go with that.
