### ISSUE TITLE
[Future request] Jetson Nano compatible?

### ISSUE THREAD

**Issue by SA7BNT** [zocker-160/handbrake-nvenc-docker#4]
Hey, 

will it be possible to use this docker for Jetson Nano in the future??
Right now im getting this error

> 0455c939b0c1: Pull complete 
Digest: sha256:3632115354039d238a7b13cce82ca982d68b3368be99b58eb004901ad96bb5bf
Status: Downloaded newer image for zocker160/handbrake-nvenc:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
c7717f95cc694134a740691cab8bb7586d98f675e9f0ab116f68a34dd02f4c6d
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.

**Comment by zocker-160** [comment]
Thanks for this request, sadly I have no Jetson Nano for testing, but it should be possible to make it work from the Docker side of things.

I am not sure though if:
- Handbrake on ARM supports NVENC
- Jetson Nano supports NVENC

**Comment by zocker-160** [comment]
ok so I did some research and according to [this](https://forums.developer.nvidia.com/t/h-264-h-265-encoding-using-jetson-nano-gpu/73839/4) the Jetson Nano does not support GPU/CUDA for hardware encoding / decoding, it rather has some own encoding hardware, which currently is not supported neither by ffmpeg nor by Handbrake.

So making this Docker work would be possible, but AFAIK you will only be able to use the CPU for the encoding.

**Comment by SA7BNT** [comment]
> this

Im using this. Running fine
https://github.com/jocover/jetson-ffmpeg

**Comment by zocker-160** [comment]
@SA7BNT yes exactly, it needs a special ffmpeg version, because it is not using the "normal" NVENC, which desktop GPUs use.

Since Handbrake does not use ffmpeg, I don't think hardware accelerated encoding will be possible without a patch for Handbrake.

**Comment by SA7BNT** [comment]
Ah ok thats sad. Ok then i will run this ffmpeg version instead. Much faster then CPU encoding. 
But will still get an eye on this git.
Maybe one day there will be a patch.

**Comment by zocker-160** [comment]
@SA7BNT you could try creating a feature request for Handbrake directly
https://github.com/HandBrake/HandBrake

But other than that, I think using that special ffmpeg version is the best solution for you right now.

**Comment by zocker-160** [comment]
closing, because I do no think that there is anything I can do here.

Handbrake would need to add support for this device in order to make it work inside docker as well.
