### ISSUE TITLE
dconf warning failled to commit changes to deconf : failed to execute child process

### ISSUE THREAD

**Issue by galosre** [zocker-160/handbrake-nvenc-docker#6]
starting a moment ago what is the fix?
``dconf warning failled to commit changes to deconf : failed to execute child process

Dbus lauch ? no file or directory

**Comment by zocker-160** [comment]
What kernel version are you using?

I sadly still cannot reproduce this error on multiple machines.

**Comment by Draakii** [comment]
4.19.0-18-AMD64

**Comment by zocker-160** [comment]
With the release of Handbrake 1.5.0 I did some testing with different hardware and software combinations, but sadly I am unable to reproduce any of the issues.

Do you also have this issue with HB 1.5.0?

**Comment by goffrier** [comment]
hello, it's me the guy with borked gpu drivers, this time i got this error kek

**Comment by goffrier** [comment]
i'm on the latest PVE kernel, i'm up to date too

**Comment by goffrier** [comment]
must be a permission issue, i did a chmod 777 on the directory, restarted container and restarted encoding, no errors, file is there

**Comment by zocker-160** [comment]
> must be a permission issue, i did a chmod 777 on the directory, restarted container and restarted encoding, no errors, file is there

@goffrier oh good to know, for what folder did you had to change the permissions?

**Comment by goffrier** [comment]
i had all the handbrake stuff in one directory, i just chmodded it

**Comment by funkadhafi** [comment]
@zocker-160  Hello there,
I'm on Debian 10 too and the problem comes from the nvenc API version. "Required: 12.1 Found: 11.1."
this is the interesting part of the Handbrake log : 
```
[h264_nvenc @ 0x7f92d502d940] Driver does not support the required nvenc API version. Required: 12.1 Found: 11.1
[h264_nvenc @ 0x7f92d502d940] The minimum required Nvidia driver for nvenc is (unknown) or newer
[20:35:53] encavcodecInit: avcodec_open failed
[20:35:53] Failure to initialise thread 'FFMPEG encoder (libavcodec)'
```

Your container work as it should, except for the nvenc part witch cant find the right version of the API but that is due to the new version of Handbrake I suppose ?
The problem is that on Debian 10, I cannot install the latest Nvidia driver. 

So I tried to revert to the previous version of the image: zocker160/handbrake-nvenc:16x then zocker160/handbrake-nvenc:15x, etc... but all the previous versions hangs with the same log in an infinite loop of this : 

```
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing... 
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing... 
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing... 
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing... 
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing... 
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing... 
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing... 
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing... 
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing... 
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing... 
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing... 
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing... 
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing... 
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] 54-check-optical-drive.sh: executing... 
looking for usable optical drives...
no usable optical drive found.
[cont-init.d] 54-check-optical-drive.sh: exited 0.
[cont-init.d] 54-check-qsv.sh: executing... 
/var/run/s6/etc/cont-init.d/54-check-qsv.sh: 8: list_cpu_features: not found
/var/run/s6/etc/cont-init.d/54-check-qsv.sh: 9: list_cpu_features: not found
Processor: 
Microarchitecture: 
Kernel: 5.10.0-0.deb10.16-amd64
/var/run/s6/etc/cont-init.d/54-check-qsv.sh: 80: lspci: not found
Intel Quick Sync Video not supported: video adapter not using i915 driver.
[cont-init.d] 54-check-qsv.sh: exited 0.
[cont-init.d] 54-check-trash-dir.sh: executing... 
/var/run/s6/etc/cont-init.d/54-check-trash-dir.sh: 9: is-bool-val-true: not found
[cont-init.d] 54-check-trash-dir.sh: exited 0.
[cont-init.d] 55-handbrake.sh: executing... 
core dump file location: core
core dump file size:  (blocks)
/var/run/s6/etc/cont-init.d/55-handbrake.sh: 49: take-ownership: not found
[cont-init.d] 55-handbrake.sh: exited 127.
[services.d] stopping services
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

My question is : how can I get the previous version of the container to work as before on my system ?
Regards

**Comment by zocker-160** [comment]
@funkadhafi 
there seem to be two separate issues at play here:

1) Handbrake 1.7 added AV1 encoding to NVenc which AFAIK requires at least API version 12.1, so there is nothing I can do about that, apart from you installing an up to date GPU driver (is 535.129.03 not available on Debian 10? I can hardly believe that)

2) Old images got broken recently it seems, despite me not changing anything? This is something I need to investigate.

**Comment by zocker-160** [comment]
I found the issue for 2), completely my fault I am very sorry, will fix asap.

**Comment by zocker-160** [comment]
Pushed updates to all versions, should fix the issue.

**Comment by funkadhafi** [comment]
@zocker-160  Thank you for repairing all previous images, the zocker160/handbrake-nvenc:16x work as expected now.
