### ISSUE TITLE
jlesage - firefox & nvidia support

### ISSUE THREAD

**Issue by ErgoProxy1337** [zocker-160/handbrake-nvenc-docker#7]
hay,

sry for asking here but, couldnt find any other method to contact u.
Is there a chance, u could do the same with the firefox version of him with nvidia support?
I tried it by my own but im not experienced enough in creating an own one.

I would rly love to have an firefox with nvidia support. Any way u could try it?

**Comment by zocker-160** [comment]
Hi,
yes I could give it a try, I wonder though what is the best way of knowing that the Nvidia GPU support is actually working?

Can you give me a description how to test Nvidia GPU functionality within Firefox?

**Comment by ErgoProxy1337** [comment]
omg I rly love u for this. Cause I have a lot of use cases where I need it. especiall for trading.

1. U should be able to see it trough `nvidia-smi` while looking at youtube
2. U have to see this unter about:support (Firefox searchbar)

As I had read, u have to force it on Linux to be used. Here some Informations:
[https://askubuntu.com/questions/491750/force-enable-hardware-acceleration-in-firefox](https://askubuntu.com/questions/491750/force-enable-hardware-acceleration-in-firefox)

Here someone who tried this but duno. For me it is not working and he makes it hard to test it.
[https://github.com/andrewmackrodt/dockerfiles/blob/master/firefox-x11/Dockerfile](https://github.com/andrewmackrodt/dockerfiles/blob/master/firefox-x11/Dockerfile)
His ubuntu base image is:
[https://github.com/andrewmackrodt/dockerfiles/blob/master/ubuntu-x11/Dockerfile](https://github.com/andrewmackrodt/dockerfiles/blob/master/ubuntu-x11/Dockerfile)

[https://wiki.debian.org/HardwareVideoAcceleration](https://wiki.debian.org/HardwareVideoAcceleration)

Hope, this helps

btw falls du discord hast, können wir auch dort schreiben und ich könnte dir versuchen auch etwas zu helfen. 
Bin selbst Entwickler in c# & javascript / react.

**Comment by ErgoProxy1337** [comment]
Alex | Shinigami#7073

**Comment by zocker-160** [comment]
will PM you and close this issue

**Comment by zocker-160** [comment]
I sent you a friend request.

**Comment by ErgoProxy1337** [comment]
hab noch keine erhalten

**Comment by zocker-160** [comment]
![Screenshot_20211109_165849](https://user-images.githubusercontent.com/36563538/140959028-5905bae3-4515-4032-aa36-787e7da2f45d.png)

**Comment by ErgoProxy1337** [comment]
ist aber `Alex | Shinigami#7073` als ganzes

**Comment by zocker-160** [comment]
o_O oh
